---

- name: Copy bashrc
  template:
    src: "bashrc.j2"
    dest: "{{ user_home_dir }}/.bashrc"
    force: yes

- name: Copy screenrc
  template:
    src: "screenrc.j2"
    dest: "{{ user_home_dir }}/.screenrc"
    force: yes

- name: Copy vimrc globally
  template:
    src: "vimrc.j2"
    dest: "/etc/vim/vimrc.local"
    force: yes

