---

- name: Prepare the mysql config location
  file:
    path: "{{ mysql.conf_dir }}"
    state: directory

- name: Ensure that mysql's log dir exists
  file:
    path: "{{ mysql.log_dir }}"
    state: directory
    mode: "u+rwX,g+rwX,o+rwX"

- name: Ensure that mysql has a writeable PID dir
  file:
    path: /var/run/mysql
    owner: mysql
    group: mysql
    state: directory
    mode: "u+rwX,g+rwX,o+rwX"

#
#
#

- name: Copy the mysql config file
  template:
    src: "my.cnf.j2"
    dest: "{{ mysql.conf_dir }}/my.cnf"
    force: yes
#  when: mysql_cnf_file_check.stat.exists == false

