---

- name: Copy our production php.ini
  template:
    src: files/php.ini.j2
    dest: "{{ php8.ini_path }}"
    force: yes

- name: Create php conf.d directory
  file:
    path: "{{ php8.conf_d_dir }}"
    mode: 777
    state: directory

- name: Prepare PECL default extension directory location
  command: "{{ php8.install_prefix }}/bin/pecl config-set ext_dir {{ php8.extension_dir }}"

- name: Prepare PECL default php ini location
  command: "{{ php8.install_prefix }}/bin/pecl config-set php_ini {{ php8.ini_path }}"

- name: PECL Channel Update pre-module install
  command: "{{ php8.install_prefix }}/bin/pecl channel-update pecl.php.net"

- name: "Install {{ php8.pecl_inotify_version }}"
  shell: "yes '' | {{ php8.install_prefix }}/bin/pecl install --force {{ php8.pecl_inotify_version }}"

- name: "Install {{ php8.pecl_memcached_version }}"
  shell: "yes '' | {{ php8.install_prefix }}/bin/pecl install --force {{ php8.pecl_memcached_version }}"

- name: "Install {{ php8.pecl_msgpack_version }}"
  shell: "yes '' | {{ php8.install_prefix }}/bin/pecl install --force {{ php8.pecl_msgpack_version }}"

# Create symlinks to php8 so that we can use php8 from the command line
- name: Remove old symlinks/files
  file: path="/usr/local/bin/{{ item }}" state=absent
  with_items:
    - php
    - php-config
    - php-cgi
    - phpize
    - pecl
    - pear
    - peardev
    - phpdbg
    - phar
  ignore_errors: true

- name: Create the symlinks (except phar)
  file: src="{{ php8.install_prefix }}/bin/{{ item }}" dest="/usr/local/bin/{{ item }}" state=link
  with_items:
    - php
    - php-config
    - php-cgi
    - phpize
    - pecl
    - pear
    - peardev
    - phpdbg

- name: Create the phar symlink (slightly different from the rest)
  file: src="{{ php8.install_prefix }}/bin/phar.phar" dest="/usr/local/bin/phar" state=link


## Update the php.ini file with all the recently installed extentions
- name: Update the php.ini file with all the added extentions
  blockinfile:
    path: "{{ php8.ini_path }}"
    insertafter: EOF
    marker: ""
    block: |
      ; Enable inotify
      extension={{ php8.extension_dir }}/inotify.so

      ; Endable memcached
      extension={{ php8.extension_dir }}/memcached.so

      ; Enable msgpack
      extension={{ php8.extension_dir }}/msgpack.so

