---

#
# Check
#

- name: Check if we've already downloaded memcached
  stat: path=/usr/local/src/memcached-{{ memcached_version }}.tar.gz
  register: memcached_file_check

#
# Install
#

#- name: Download memcached
#  get_url:
#    url: "{{ memcached_download_url }}"
#    dest: "/usr/local/src/memcached-{{ memcached_version }}.tar.gz"
#  when: memcached_file_check.stat.exists == false

- name: Copy php {{ memcached_version }}
  copy: src={{ deployment_resource_dir }}/memcached-{{ memcached_version }}.tar.gz dest=/usr/local/src/memcached-{{ memcached_version }}.tar.gz
  when: nginx_file_check.stat.exists == false

- name: Unzip memcached archive
  unarchive:
    src: /usr/local/src/memcached-{{ memcached_version }}.tar.gz
    dest: /usr/local/src
    #creates: /usr/local/src/memcached-{{ memcached_version }}
    copy: no
    owner: root
    group: root

- name: memcached configure
  shell: ./configure --prefix={{ memcached_install_prefix }}
  args:
    chdir: /usr/local/src/memcached-{{ memcached_version }}

- name: memcached make
  command: chdir=/usr/local/src/memcached-{{ memcached_version }} make

- name: memcached make install
  command: chdir=/usr/local/src/memcached-{{ memcached_version }} make install

- name: Copy memcached binary to /usr/bin
  copy: src={{ memcached_install_prefix }}/bin/memcached dest=/usr/bin/memcached force=yes mode=0755


