
# defaults
host_key_checking: false # for testing
deployment_resource_dir: /usr/local/src/ansible-files
base_user_name: djet

# OPENSSL
openssl:
  version: 1.1.1q
  download_url: https://www.openssl.org/source/openssl-1.1.1q.tar.gz
  install_prefix: /usr/local/openssl

# CURL
curl:
  version: 7.85.0
  download_url: https://curl.se/download/curl-7.85.0.tar.gz
  install_prefix: /usr/local/curl

# MEMCACHED
memcached:
  version: 1.6.17
  download_url: https://memcached.org/files/memcached-1.6.17.tar.gz
  install_prefix: /usr/local/memcached

# NGINX
nginx:
  version: 1.22.1
  download_url: http://nginx.org/download/nginx-1.22.1.tar.gz
  install_prefix: /usr/local/nginx
  sbin_path: /usr/local/sbin/nginx
  conf_path: /etc/nginx
  configure_options: "--user=nobody --group=www-data --with-debug --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-file-aio --with-threads"

# PHP
php8:
  version: 8.1.11
  download_url: https://www.php.net/distributions/php-8.1.11.tar.xz
  install_prefix: /usr/local/php8
  configure_options: "--with-pear --with-readline --with-mysqli --with-zlib --enable-intl --with-gettext --with-pspell --with-curl --enable-mbstring --with-tidy --enable-soap --with-openssl --enable-bcmath --enable-opcache --with-pdo-mysql=mysqlnd --enable-pcntl --enable-fpm --enable-gd --with-jpeg --with-webp --with-freetype --with-zip"
  conf_d_dir: /usr/local/php8/conf.d # for xdebug to allow quick enable/disable
  extension_dir: /usr/local/php8/modules
  ini_path: /usr/local/php8/lib/php.ini
  pecl_inotify_version: inotify
  pecl_memcached_version: memcached
  pecl_msgpack_version: msgpack


# MYSQL
mysql:
  version_x86: 8.0.25-15-Linux.x86_64.glibc2.12-minimal
  download_url_x86: https://downloads.percona.com/downloads/Percona-Server-LATEST/Percona-Server-8.0.25-15/binary/tarball/Percona-Server-8.0.25-15-Linux.x86_64.glibc2.12-minimal.tar.gz
  version_arm: 8.0.25-15-aarch64-minimal
  download_url_arm: DOES_NOT_EXIST_YET
  install_prefix: /usr/local/mysql
  data_dir: /var/local/mysql/data
  conf_dir: /etc/mysql
  log_dir: /var/log/mysql

# COMPOSER
composer:
  update_script_file: /usr/local/bin/composer-update


