
# defaults
host_key_checking: false # for testing
deployment_resource_dir: /usr/local/src/ansible-files

# blah
nginx_version: 1.15.8
nginx_download_url: http://192.168.0.207/nginx-{{ nginx_version }}.tar.gz
nginx_install_prefix: /usr/local/nginx
nginx_sbin_path: /usr/sbin/nginx
nginx_conf_path: /usr/local/nginx/conf/nginx.conf
nginx_custom_modules: "--with-debug --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-file-aio --with-threads"

php7_version: php-7.3.1
php7_download_url: http://192.168.0.207/{{ php7_version }}.tar.xz # http://ca1.php.net/get/php-7.3.2.tar.gz/from/this/mirror
php7_install_prefix: /usr/local/php7
php7_extension_dir: /usr/local/php7/modules
php7_ini_path: /usr/local/php7/lib/php.ini
php7_custom_modules: "--with-gd --with-mysqli --with-zlib --enable-inline-optimization --with-gettext --with-pspell --with-curl --enable-mbstring --with-jpeg-dir=/usr/lib --with-freetype-dir=/usr --with-tidy --enable-soap --enable-zip --with-openssl --enable-bcmath --enable-opcache --with-pdo-mysql=mysqlnd --enable-pcntl --enable-fpm --with-libzip"
php7_pecl_inotify_version: inotify
php7_pecl_memcached_version: memcached
php7_pecl_rdkafka_version: rdkafka

memcached_version: memcached-1.5.12
memcached_download_url: http://192.168.0.207/{{ memcached_version }}.tar.gz # https://memcached.org/files/memcached-1.5.12.tar.gz
memcached_install_prefix: /usr/local/memcached

mysql_version: Percona-Server-8.0.13-4-Linux.x86_64.ssl102
mysql_download_url: http://192.168.0.207/{{ mysql_version }}.tar.gz
mysql_install_prefix: /usr/local/mysql
mysql_data_dir: /var/local/mysql/data
mysql_conf_path: /etc/mysql/my.cnf



