---

#
# Check
#

- name: Install necessary packages
  apt: 
    name: "{{ packages }}" 
    state: present
  vars:
    packages:
    - libssl-dev
    - libpcre3-dev
    - zlib1g-dev

- name: Check if we've already downloaded nginx
  stat: path=/usr/local/src/nginx-{{ nginx.version }}.tar.gz
  register: nginx_file_check

- name: Check if we've already extracted nginx
  stat: path=/usr/local/src/nginx-{{ nginx.version }}
  register: nginx_extract_check

- name: Check if symlink exists
  stat: path={{ nginx.sbin_path }}
  register: nginx_symlink_check

- name: Stop nginx service if running before install
  systemd:
    name: nginx
    state: stopped
  register: service_status_nginx
  ignore_errors: true

#
# Deploy
#

#- name: Download nginx
#  get_url:
#    url: "{{ nginx.download_url }}"
#    dest: "/usr/local/src/nginx-{{ nginx.version }}.tar.gz"
#  when: nginx_file_check.stat.exists == false

- name: Ensure that config directory exists
  file:
    path: "{{ nginx.conf_path }}"
    state: directory
    owner: nobody
    group: www-data

# - name: Generate a large Diffie-Hellman prime with default size (4096 bits) - WILL TAKE A LONG TIME IF NOT PRESENT YET
#   openssl_dhparam:
#     path: /etc/nginx/dhparam.pem 

- name: Copy a already generated large Diffie-Hellman prime with default size (4096 bits) Much faster than creating it each time
  copy:
    src: "files/dhparam.pem"
    dest: "/etc/nginx/dhparam.pem"
    force: yes
  
- name: Download nginx-{{ nginx.version }}.tar.gz
  get_url:
    url: "{{ nginx.download_url }}"
    dest: "/usr/local/src/nginx-{{ nginx.version }}.tar.gz"
  when: nginx_file_check.stat.exists == false

- name: Remove extracted nginx if it exists
  file:
    path: /usr/local/src/nginx-{{ nginx.version }}
    state: absent
  when: nginx_extract_check.stat.exists == true

- name: Extract nginx
  unarchive: 
    src: /usr/local/src/nginx-{{ nginx.version }}.tar.gz
    dest: /usr/local/src
    creates: /usr/local/src/nginx-{{ nginx.version }}
    copy: no
    owner: root
    group: root

- name: Configure
  shell: "./configure --prefix={{ nginx.install_prefix }} --conf-path={{ nginx.conf_path }}/nginx.conf --with-openssl=/usr/local/src/openssl-{{ openssl.version }} {{ nginx.configure_options }}"
  args:
    chdir: /usr/local/src/nginx-{{ nginx.version }}

- name: Running make, this might take a bit
  shell: make -j$(nproc)
  args:
    chdir: "/usr/local/src/nginx-{{ nginx.version }}"

- name: Running make install
  command: make install
  args:
    chdir: "/usr/local/src/nginx-{{ nginx.version }}"

- name: Destroy the old symlink if it exists
  file:
    path: "{{ nginx.sbin_path }}"
    state: absent
  when: nginx_symlink_check.stat.exists == true

- name: Create the symlink
  file:
    src: "{{ nginx.install_prefix }}/sbin/nginx"
    dest: "{{ nginx.sbin_path }}"
    state: link

- name: Set up log dir permissions (any existing ones too)
  file:
    path: "/var/log/nginx"
    group: www-data
    mode: "g+w"
    recurse: yes
    state: directory

- name: Restart nginx service if running before install
  systemd:
    name: nginx
    state: started
  ignore_errors: true
  when: service_status_nginx.failed == false and service_status_nginx.state == 'stopped'
