---

- hosts: development
  remote_user: vagrant
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - apt-core

    - { role: nginx-install, tags: ["nginx", "nginx-install"] }
    - { role: nginx-config, tags: ["nginx", "nginx-config"] }
    - { role: nginx-service, tags: ["nginx", "nginx-service"] }

    - { role: php-install, tags: ["php", "php-install"] }
    - { role: php-config, tags: ["php", "php-config"] }
    - { role: php-fpm-config, tags: ["php", "php-fpm-config"] }
    - { role: php-fpm-service, tags: ["php", "php-fpm-service"] }

    - { role: memcached-install, tags: ["memcached", "memcached-install"] }
    - { role: memcached-config, tags: ["memcached", "memcached-config"] }
    - { role: memcached-service, tags: ["memcached", "memcached-service"] }

    - { role: mysql-install, tags: ["mysql", "mysql-install"] }
    - { role: mysql-config, tags: ["mysql", "mysql-config"] }
    - { role: mysql-service, tags: ["mysql", "mysql-service"] }
