---

- name: Copy our php8-fpm systemd service config
  copy:
    src: files/php8-fpm.service
    dest: /etc/systemd/system/php8-fpm.service

- name: Enable php8-fpm service
  systemd:
    name: php8-fpm
    daemon_reload: yes
    enabled: yes
    state: started

