---

- debug: msg="Distribution {{ ansible_distribution }} version {{ ansible_distribution_major_version }} on {{ ansible_architecture }}"

- name: Update the hostname
  hostname: name={{ base_user_name }}.test

- name: Add dev hostname to /etc/hosts for NS resolution
  lineinfile:
    dest: "/etc/hosts"
    line: "127.0.0.1 {{ base_user_name }}.test"
    insertafter: "^127.0.0.1 localhost"

- name: Set our preferred timezone
  shell: timedatectl set-timezone America/Vancouver
